version: "3.9"
services:
  order-db:
    image: mysql
    container_name: order-db
    ports:
      - "3307:3306"
    volumes:
      - order-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: orders
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8080:8080"
    depends_on:
      - order-db
  product-db:
    image: mysql
    container_name: product-db
    ports:
      - "3308:3307"
    volumes:
      - product-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: products
      MYSQL_TCP_PORT: 3307
  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      - product-db
volumes:
  order-data:
  product-data: